version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./dump_23-09-2018_19_24_30.sql:/docker-entrypoint-initdb.d/dump_23-09-2018_19_24_30.sql
    environment:
      - POSTGRES_USER:'migiwara'
      - POSTGRES_DB:'sustainabilitydb'
      - POSTGRES_PASSWORD:'qatar123'
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
  django:
    build: .
#    command: ["python", "manage.py", "migrate"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:80"]
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
  celery:
    build: .
    command: celery -A backend worker -l info -f celery.logs
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  node-modules:
