export const COLLECTION_IS_LOADING = "PREDICTIONS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_PREDICTIONS";
export const RECEIVED_MODEL = "RECEIVED_PREDICTION";
export const REMOVED_MODEL = "REMOVED_MODEL";
export const UPDATE_COLLECTION_QUERY = "UPDATE_PREDICTION_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_MODEL,
    REMOVED_MODEL,
    UPDATE_COLLECTION_QUERY
};
