export const COLLECTION_IS_LOADING = "RECORDS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_RECORDS";
export const RECEIVED_MODEL = "RECEIVED_RECORD";
export const REMOVED_MODEL = "REMOVED_MODEL";
export const UPDATE_COLLECTION_QUERY = "UPDATE_RECORDS_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_MODEL,
    REMOVED_MODEL,
    UPDATE_COLLECTION_QUERY
};
