# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-29 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_secret', models.CharField(max_length=100)),
                ('sgv', models.IntegerField()),
                ('direction', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('dateString', models.CharField(max_length=100)),
                ('rawData', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_records',
                'managed': True,
            },
        ),
    ]
