# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='rawData',
            field=models.CharField(default='', max_length=500),
        ),
    ]
