# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-30 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180830_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='date',
            new_name='sysTime',
        ),
    ]
