export const COLLECTION_IS_LOADING = "DECISIONS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_DECISIONS";
export const RECEIVED_MODEL = "RECEIVED_DECISION";
export const REMOVED_MODEL = "REMOVED_MODEL";
export const UPDATE_COLLECTION_QUERY = "UPDATE_DECISIONS_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_MODEL,
    REMOVED_MODEL,
    UPDATE_COLLECTION_QUERY
};